PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>  
PREFIX  ont:  <http://webprotege.stanford.edu/projectOntology#>  
PREFIX  db:   <http://dbpedia.org/ontology/>  
SELECT ?homeless ?year WHERE {  
    ?z db:Year ?year .  
    ?z ont:NumOfHomeless ?homeless .  
    ?z ont:CountyName '§0' .  
    {  
        SELECT ?salary ?year WHERE {  
            ?x ont:SalaryValue ?salary .  
            ?x db:Year ?year .  
            ?x ont:CountyName '§0' .  
        } ORDER BY DESC(xsd:float(?salary)) LIMIT 1  
    }}